---
title: Aurelitec
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  reviews:
    title: Reviews
    output: false
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: true
description: Creating free out of the box programs and apps since 1999
author: aurelitec
twitter:
  username: aurelitec
gems:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
