# Jekyll SEO Tag plugin
title       : "Aurelitec"
description : "Creating free out of the box programs and apps since 1999"
author      : aurelitec
twitter:
  username  : aurelitec

collections:
  - reviews
  - testimonials

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

repository: aurelitec/aurelitec.github.io

custom:
  url: https://www.aurelitec.com
