# Jekyll SEO Tag plugin
title       : "Aurelitec"
description : "Creating free out of the box programs and apps since 1999"
author      : aurelitec
twitter:
  username  : aurelitec

github:
  url: http://localhost:4000

baseurl: "http://www.aurelitec.com"

collections:
  - reviews
  - testimonials

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
